packages:
  - apps/*
  - packages/*

catalogs:
  prisma:
    prisma: ^7.9.1

# Needed for ESLint to resolve workspace deps.
# https://github.com/pnpm/pnpm/issues/4741#issuecomment-1177965681
nodeLinker: hoisted

publicHoistPattern:
  - '*@prisma*'
  - '*pg*'
  - '*ioredis*'
  - '*import-in-the-middle*'
  - '*require-in-the-middle*'
  - '*@opentelemetry*'
  - '*@sentry*'

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
